version: '3.8'

services:
  genezio:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: genezio_tests
    secrets:
      - genezio_token
    working_dir: /root/genezio/tests/integration
    command: 
      - /bin/bash
      - -c
      - |
        echo -n "genezio version: " && genezio --version
        cat /run/secrets/genezio_token > ~/.geneziorc
        genezio account
        python3 test_hello.py
        python3 test_cron.py
        python3 test_webhook.py
        python3 test_todo_list.py
        python3 test_blockchain.py
        python3 test_hello_ts.py
        python3 test_todo_list_ts.py
        python3 test_hello_local.py
        python3 test_hello_add_class.py

# Create `.env.genezio_token` locally in the repo and paste in it a valid `dev` genezio token
secrets:
  genezio_token:
    file: .env.genezio_token
    name: genezio_token
