version: '3.8'

# Notes:
# - Running this docker-compose file will deploy the example projects in the genezio account referenced by the GENEZIO_TOKEN
# - `~/.geneziorc` should contain a valid genezio auth token for the correspongin env (dev or prod)
# - You can redefine TEST_LIST to run a subset of the tests
# To test locally run:
# export GENEZIO_TOKEN=$(cat ~/.geneziorc) && docker-compose up --force-recreate --abort-on-container-exit --exit-code-from genezio
services:
  genezio:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - STAGE=dev
        - GENEZIO_TOKEN=${GENEZIO_TOKEN}
    container_name: genezio_tests
    environment:
      TEST_LIST: "test_hello.py test_cron.py test_webhook.py test_todo_list.py test_blockchain.py test_hello_ts.py test_todo_list_ts.py test_hello_local.py"
    secrets:
      - GENEZIO_TOKEN
    working_dir: /root/genezio/tests/integration
    command: 
      - /bin/bash
      - -c
      - |
        echo -n $GENEZIO_TOKEN > ~/.geneziorc 
        echo -n $$TEST_LIST | xargs -n 1 python3

# To test locally run `export GENEZIO_TOKEN=$(cat ~/.geneziorc)`
# `~/.geneziorc` should contain a valid `dev` genezio auth token
secrets:
  GENEZIO_TOKEN:
    external: true